spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.58:8848
        namespace: public
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #    url: jdbc:mysql://140.143.161.107:3306/mail?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://192.168.0.58:3306/mall?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Q1w2e3r4t5-
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.0.58
    virtual-host: /order
    port: 5672
    username: user
    password: user
    connection-timeout: 15000
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
  redis:
    database: 0
    host: 192.168.0.58
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: cn.wwtianmei.qingyun.stock.entity
#dubbo:
#  registry:
#    # 挂载到 Spring Cloud 注册中心
#    address: spring-cloud://192.168.0.58
#  cloud:
#    subscribed-services: product-service
#  provider:
#    serialization: kryo
logging:
  level:
    org.springframework.web: TRACE
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always