spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.58:8848
        namespace: public
  application:
    name: oauth2-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #    url: jdbc:mysql://140.143.161.107:3306/mail?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    jdbc-url: jdbc:mysql://192.168.0.58:3306/oauth2?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: Q1w2e3r4t5-
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
mybatis:
  type-aliases-package: cn.wwtianmei.qingyun.oauth2.server.entity
  mapper-locations: classpath:mapper/*.xml